/*
Copyright 2026 Sadra Mohtadi

Licensed under the Apache License, Version 2.0
http://www.apache.org/licenses/LICENSE-2.0
*/

// All the functions and code for the different themes
function theme() {
  return {
    apply(themeObj) {
      Object.entries(themeObj).forEach(([variable, value]) => {
        document.documentElement.style.setProperty(variable, value);
      });
    },

    reset() {
      const root = document.documentElement;
      Array.from(document.styleSheets)
        .flatMap(sheet => {
          try { return Array.from(sheet.cssRules); } catch { return []; }
        })
        .filter(rule => rule.selectorText === ':root')
        .flatMap(rule => Array.from(rule.style))
        .filter(prop => prop.startsWith('--color-'))
        .forEach(prop => root.style.removeProperty(prop));
    }
  };
}

// The CSS values for different themes
const themes = {

  // Default
  // Restores every token to the original values from both CSS files
  default: {
    // styles.css tokens
    '--color-page-bg':                        'rgb(56, 56, 56)',
    '--color-devpanel-bar-bg':                'rgb(87, 87, 87)',
    '--color-devpanel-bar-text':              'whitesmoke',
    '--color-devpanel-system-bg':             'rgb(214, 214, 214)',
    '--color-phone-bezel':                    '#333',
    '--color-phone-screen':                   'white',
    '--color-phone-content-bg':               'rgb(37, 37, 36)',
    '--color-dynamic-island-bg':              'black',
    '--color-footer-text':                    'rgb(122, 122, 122)',
    '--color-header-primary':                 '#222425',
    '--color-header-secondary':               '#121213',
    '--color-progress-text':                  'black',
    '--color-progress-track':                 'gray',
    '--color-progress-fill':                  'rgb(0, 110, 255)',
    '--color-feed-ctrl-bg':                   'rgba(255, 255, 255, 0.18)',
    '--color-feed-ctrl-border':               'rgba(255, 255, 255, 0.45)',
    '--color-feed-ctrl-border-dim':           'rgba(255, 255, 255, 0.2)',
    '--color-feed-sel-bg':                    'rgba(255, 255, 255, 0.25)',
    '--color-feed-sel-border':                'rgba(255, 255, 255, 0.5)',
    '--color-feed-sel-text':                  'rgba(30, 30, 30, 0.75)',
    '--color-feed-sel-hover-bg':              'rgba(255, 255, 255, 0.4)',
    '--color-feed-sel-dark-bg':               'rgba(20, 20, 30, 0.55)',
    '--color-feed-sel-dark-bg-light':         'rgba(20, 20, 30, 0.45)',
    '--color-feed-sel-border-dim':            'rgba(255, 255, 255, 0.15)',
    '--color-feed-sel-border-top':            'rgba(255, 255, 255, 0.25)',
    '--color-feed-sel-selected-text':         'rgba(255, 255, 255, 0.92)',
    '--color-feed-sel-active-text':           'rgba(255, 255, 255, 0.85)',
    '--color-btn-primary-bg':                 '#0054E9',
    '--color-btn-primary-border':             '#005cfa',
    '--color-btn-primary-text':               'rgb(238, 238, 238)',
    '--color-btn-primary-active-bg':          '#004ac9',
    '--color-btn-primary-active-border':      '#004bce',
    '--color-btn-secondary-bg':               '#f3f5f8',
    '--color-btn-secondary-text':             'rgb(17, 17, 17)',
    '--color-btn-secondary-border':           '#ffffff',
    '--color-btn-secondary-active-bg':        '#ced1d4',
    '--color-btn-secondary-active-border':    '#d6d6d6',
    '--color-nav-bg':                         'rgba(51, 51, 51, 0.459)',
    '--color-nav-item-bg':                    'rgba(32, 32, 32, 0.432)',
    '--color-nav-item-text':                  '#EEEEEE',
    '--color-nav-item-selected-bg':           '#0054E9',
    '--color-results-panel-bg':               '#f1a413',
    '--color-result-card-border':             'rgb(243, 239, 239)',
    '--color-result-hide-bar':                'rgb(243, 239, 239)',
    '--color-result-view-more-bg':            'rgba(255, 255, 255, 0.075)',
    '--color-result-view-more-border':        'gray',
    '--color-result-source-label':            'rgb(44, 51, 54)',
    '--color-result-badge-text':              'rgb(248, 242, 242)',
    '--color-result-badge-bg':                'rgb(41, 40, 40)',
    '--color-result-title-text':              'rgb(10, 10, 10)',
    '--color-infobox-bg':                     'rgb(255, 251, 238)',
    '--color-infobox-text':                   '#051b2c',
    '--color-ai-warn-neutral':                '#666262',
    '--color-ai-warn-mid':                    '#8a2b2b',
    '--color-ai-warn-hot':                    '#d10707',
    '--color-chart-border':                   'rgb(245, 245, 245)',
    '--color-chart-bg':                       'rgba(255, 204, 50, 0.302)',
    '--color-thrift-item-text':               '#0A0A0A',
    '--color-thrift-img-border':              'white',
    '--color-source-card-border':             'rgb(245, 245, 245)',
    '--color-source-meta-text':               'rgb(117, 117, 117)',
    '--color-search-icon':                    '#dbd9d9',
    '--color-search-text':                    '#e6e6e6',
    '--color-account-link':                   '#3232a3',
    // settings.css tokens
    '--color-settings-info-text':             'rgb(68, 68, 68)',
    '--color-settings-back-link':             'rgb(18, 18, 246)',
    '--color-settings-link':                  '#3232a3',
    '--color-settings-divider':               '#3a3e41',
    '--color-settings-option-text':           '#272a2b',
    '--color-settings-option-icon':           '#1c1e1f',
    '--color-settings-donate-accent':         '#5A3AD8',
    '--color-settings-desc-text':             '#474747',
    '--color-settings-priority-bg':           '#ebedf1',
    '--color-settings-separator':             'black',
  },


  // Dark mode
  // OLED-friendly, battery saver, less strain on the eyes
  dark_mode: {
    '--color-page-bg':                        'rgb(10, 10, 10)',
    '--color-phone-bezel':                    '#111',
    '--color-phone-screen':                   '#0d0d0d',
    '--color-phone-content-bg':               'rgb(15, 15, 15)',
    '--color-dynamic-island-bg':              '#000',
    '--color-footer-text':                    'rgb(80, 80, 80)',
    '--color-header-primary':                 '#d0d0d0',
    '--color-header-secondary':               '#aaaaaa',
    '--color-progress-track':                 '#333',
    '--color-progress-fill':                  '#1a7fff',
    '--color-progress-text':                  'white',
    '--color-btn-primary-bg':                 '#1040b8',
    '--color-btn-primary-border':             '#1a56db',
    '--color-btn-primary-active-bg':          '#0d3490',
    '--color-btn-primary-active-border':      '#0f3aaa',
    '--color-btn-secondary-bg':               '#1e1e1e',
    '--color-btn-secondary-text':             '#cccccc',
    '--color-btn-secondary-border':           '#333',
    '--color-btn-secondary-active-bg':        '#2c2c2c',
    '--color-btn-secondary-active-border':    '#444',
    '--color-nav-bg':                         'rgba(0, 0, 0, 0.8)',
    '--color-nav-item-bg':                    'rgba(20, 20, 20, 0.85)',
    '--color-nav-item-text':                  '#cccccc',
    '--color-nav-item-selected-bg':           '#1040b8',
    '--color-results-panel-bg':               '#1a1a1a',
    '--color-result-card-border':             '#2a2a2a',
    '--color-result-hide-bar':                '#2a2a2a',
    '--color-result-view-more-bg':            'rgba(255, 255, 255, 0.04)',
    '--color-result-view-more-border':        '#333',
    '--color-result-source-label':            '#888',
    '--color-result-badge-text':              '#ddd',
    '--color-result-badge-bg':                '#333',
    '--color-result-title-text':              '#e0e0e0',
    '--color-infobox-bg':                     '#252525',
    '--color-infobox-text':                   '#c8d8e8',
    '--color-chart-border':                   '#333',
    '--color-chart-bg':                       'rgba(255, 180, 0, 0.12)',
    '--color-thrift-item-text':               '#ddd',
    '--color-thrift-img-border':              '#444',
    '--color-source-card-border':             '#333',
    '--color-source-meta-text':               '#666',
    '--color-search-icon':                    '#444',
    '--color-search-text':                    '#888',
    '--color-account-link':                   '#5588ff',
    '--color-settings-text':                  'rgb(245, 245, 245)',
    '--color-settings-info-text':             'rgb(100, 100, 100)',
    '--color-settings-back-link':             '#5588ff',
    '--color-settings-link':                  '#5588ff',
    '--color-settings-divider':               '#2a2e31',
    '--color-settings-option-text':           '#ffffff',
    '--color-settings-option-icon':           '#ffffff',
    '--color-settings-donate-accent':         '#7c6ad8',
    '--color-settings-desc-text':             '#888888',
    '--color-settings-priority-bg':           '#1e2124',
    '--color-settings-separator':             '#444444',
  },


  // Warm amber (just for fun)
  warmAmber: {
    '--color-page-bg':                        'rgb(40, 32, 20)',
    '--color-phone-bezel':                    '#4a3520',
    '--color-phone-screen':                   '#fff8ee',
    '--color-phone-content-bg':               'rgb(30, 22, 10)',
    '--color-footer-text':                    'rgb(160, 130, 80)',
    '--color-header-primary':                 '#3a2800',
    '--color-header-secondary':               '#2a1a00',
    '--color-progress-fill':                  '#e07b00',
    '--color-progress-text':                  '#3a1a00',
    '--color-btn-primary-bg':                 '#c06000',
    '--color-btn-primary-border':             '#e07a00',
    '--color-btn-primary-active-bg':          '#9a4e00',
    '--color-btn-primary-active-border':      '#b56000',
    '--color-nav-item-selected-bg':           '#c06000',
    '--color-results-panel-bg':               '#f1a413',
    '--color-infobox-bg':                     'rgb(255, 248, 220)',
    '--color-infobox-text':                   '#3a1a00',
    '--color-account-link':                   '#9a4400',
    '--color-settings-info-text':             '#7a5a30',
    '--color-settings-back-link':             '#c06000',
    '--color-settings-link':                  '#9a4400',
    '--color-settings-divider':               '#6a4a20',
    '--color-settings-option-text':           '#3a2000',
    '--color-settings-option-icon':           '#2a1800',
    '--color-settings-donate-accent':         '#9a6000',
    '--color-settings-desc-text':             '#7a5a30',
    '--color-settings-priority-bg':           '#fff0d0',
    '--color-settings-separator':             '#6a4a20',
  },

  // Forest green
  // (again just for fun)
  forestGreen: {
    '--color-page-bg':                        'rgb(18, 32, 18)',
    '--color-phone-bezel':                    '#1a3020',
    '--color-phone-screen':                   '#eef4ee',
    '--color-phone-content-bg':               'rgb(14, 26, 14)',
    '--color-footer-text':                    'rgb(90, 130, 90)',
    '--color-header-primary':                 '#1a3a1a',
    '--color-header-secondary':               '#0f280f',
    '--color-progress-fill':                  '#2d8a2d',
    '--color-progress-track':                 '#1a3a1a',
    '--color-btn-primary-bg':                 '#1e6e1e',
    '--color-btn-primary-border':             '#28922a',
    '--color-btn-primary-active-bg':          '#155515',
    '--color-btn-primary-active-border':      '#1e7020',
    '--color-nav-bg':                         'rgba(10, 25, 10, 0.75)',
    '--color-nav-item-bg':                    'rgba(18, 38, 18, 0.7)',
    '--color-nav-item-selected-bg':           '#1e6e1e',
    '--color-results-panel-bg':               '#2d7a2d',
    '--color-result-card-border':             '#c8e8c8',
    '--color-result-hide-bar':                '#c8e8c8',
    '--color-result-view-more-bg':            'rgba(100, 200, 100, 0.07)',
    '--color-result-view-more-border':        '#2a5a2a',
    '--color-result-source-label':            'rgb(20, 60, 20)',
    '--color-result-badge-text':              'rgb(220, 248, 220)',
    '--color-result-badge-bg':                'rgb(15, 45, 15)',
    '--color-result-title-text':              '#0a1f0a',
    '--color-infobox-bg':                     'rgb(238, 248, 238)',
    '--color-infobox-text':                   '#f5fcf5',
    '--color-account-link':                   '#2a7a2a',
    '--color-settings-info-text':             '#c3cec3',
    '--color-settings-back-link':             '#2a8a2a',
    '--color-settings-link':                  '#2a7a2a',
    '--color-settings-divider':               '#1e4a1e',
    '--color-settings-option-text':           '#bfd3bf',
    '--color-settings-option-icon':           '#8f9b8f',
    '--color-settings-donate-accent':         '#4a8a2a',
    '--color-settings-desc-text':             '#4a7a4a',
    '--color-settings-priority-bg':           '#dff0df',
    '--color-settings-separator':             '#1e4a1e',
  },


  // High contrast
  // WCAG AAA. Maximum legibility for low vision users
  // Pure black + white + single vivid yellow accent. Zero ambiguous grays
  highContrast: {
    '--color-page-bg':                        '#000000',
    '--color-phone-bezel':                    '#ffffff',
    '--color-phone-screen':                   '#000000',
    '--color-phone-content-bg':               '#000000',
    '--color-dynamic-island-bg':              '#ffffff',
    '--color-footer-text':                    '#ffffff',
    '--color-header-primary':                 '#ffffff',
    '--color-header-secondary':               '#ffffff',
    '--color-progress-track':                 '#555555',
    '--color-progress-fill':                  '#ffff00',
    '--color-progress-text':                  '#000000',
    '--color-feed-ctrl-bg':                   'rgba(255, 255, 255, 0.9)',
    '--color-feed-ctrl-border':               '#ffffff',
    '--color-feed-ctrl-border-dim':           '#ffffff',
    '--color-feed-sel-bg':                    'rgba(255, 255, 255, 0.9)',
    '--color-feed-sel-border':                '#ffffff',
    '--color-feed-sel-text':                  '#000000',
    '--color-feed-sel-hover-bg':              '#ffff00',
    '--color-feed-sel-dark-bg':               '#000000',
    '--color-feed-sel-dark-bg-light':         '#111111',
    '--color-feed-sel-border-dim':            '#ffffff',
    '--color-feed-sel-border-top':            '#ffffff',
    '--color-feed-sel-selected-text':         '#000000',
    '--color-feed-sel-active-text':           '#000000',
    '--color-btn-primary-bg':                 '#ffff00',
    '--color-btn-primary-border':             '#ffffff',
    '--color-btn-primary-text':               '#000000',
    '--color-btn-primary-active-bg':          '#cccc00',
    '--color-btn-primary-active-border':      '#ffffff',
    '--color-btn-secondary-bg':               '#ffffff',
    '--color-btn-secondary-text':             '#000000',
    '--color-btn-secondary-border':           '#000000',
    '--color-btn-secondary-active-bg':        '#dddddd',
    '--color-btn-secondary-active-border':    '#000000',
    '--color-nav-bg':                         '#000000',
    '--color-nav-item-bg':                    '#111111',
    '--color-nav-item-text':                  '#ffffff',
    '--color-nav-item-selected-bg':           '#ffff00',
    '--color-results-panel-bg':               '#1a1a1a',
    '--color-result-card-border':             '#ffffff',
    '--color-result-hide-bar':                '#ffffff',
    '--color-result-view-more-bg':            '#222222',
    '--color-result-view-more-border':        '#ffffff',
    '--color-result-source-label':            '#cccccc',
    '--color-result-badge-text':              '#000000',
    '--color-result-badge-bg':                '#ffff00',
    '--color-result-title-text':              '#ffffff',
    '--color-infobox-bg':                     '#1a1a1a',
    '--color-infobox-text':                   '#ffffff',
    '--color-ai-warn-neutral':                '#ffff00',
    '--color-ai-warn-mid':                    '#ff8800',
    '--color-ai-warn-hot':                    '#ff0000',
    '--color-chart-border':                   '#ffffff',
    '--color-chart-bg':                       'rgba(255, 255, 0, 0.15)',
    '--color-thrift-item-text':               '#ffffff',
    '--color-thrift-img-border':              '#ffffff',
    '--color-source-card-border':             '#ffffff',
    '--color-source-meta-text':               '#cccccc',
    '--color-search-icon':                    '#555555',
    '--color-search-text':                    '#ffffff',
    '--color-account-link':                   '#ffff00',
    '--color-settings-info-text':             '#ffffff',
    '--color-settings-back-link':             '#ffff00',
    '--color-settings-link':                  '#ffff00',
    '--color-settings-divider':               '#ffffff',
    '--color-settings-option-text':           '#ffffff',
    '--color-settings-option-icon':           '#ffffff',
    '--color-settings-donate-accent':         '#ff88ff',
    '--color-settings-desc-text':             '#cccccc',
    '--color-settings-priority-bg':           '#222222',
    '--color-settings-separator':             '#ffffff',
  },


  // Red-green color blindness (deuteranopia & protanopia)
  // No red/green distinction is used anywhere.
  deuteranopia: {
    '--color-page-bg':                        'rgb(30, 30, 40)',
    '--color-phone-bezel':                    '#1a1a2a',
    '--color-phone-screen':                   '#f5f5ff',
    '--color-phone-content-bg':               'rgb(22, 22, 35)',
    '--color-dynamic-island-bg':              '#000010',
    '--color-footer-text':                    'rgb(100, 100, 140)',
    '--color-header-primary':                 '#1a1a30',
    '--color-header-secondary':               '#10102a',
    '--color-progress-track':                 '#3a3a5a',
    '--color-progress-fill':                  '#0072B2',
    '--color-progress-text':                  '#f5f5ff',
    '--color-btn-primary-bg':                 '#0072B2',
    '--color-btn-primary-border':             '#0090e0',
    '--color-btn-primary-text':               '#ffffff',
    '--color-btn-primary-active-bg':          '#005a8e',
    '--color-btn-primary-active-border':      '#0072B2',
    '--color-btn-secondary-bg':               '#e8e8f5',
    '--color-btn-secondary-text':             '#1a1a30',
    '--color-btn-secondary-border':           '#aaaacc',
    '--color-btn-secondary-active-bg':        '#c8c8e8',
    '--color-btn-secondary-active-border':    '#8888aa',
    '--color-nav-bg':                         'rgba(10, 10, 30, 0.8)',
    '--color-nav-item-bg':                    'rgba(20, 20, 50, 0.7)',
    '--color-nav-item-text':                  '#e0e0ff',
    '--color-nav-item-selected-bg':           '#0072B2',
    '--color-results-panel-bg':               '#E69F00',
    '--color-result-card-border':             '#f0f0ff',
    '--color-result-hide-bar':                '#f0f0ff',
    '--color-result-view-more-bg':            'rgba(255,255,255,0.08)',
    '--color-result-view-more-border':        '#aaaacc',
    '--color-result-source-label':            '#444460',
    '--color-result-badge-text':              '#f5f5ff',
    '--color-result-badge-bg':                '#333350',
    '--color-result-title-text':              '#0a0a20',
    '--color-infobox-bg':                     'rgb(240, 240, 255)',
    '--color-infobox-text':                   '#0a0a30',
    '--color-ai-warn-neutral':                '#888888',
    '--color-ai-warn-mid':                    '#D55E00',
    '--color-ai-warn-hot':                    '#D55E00',
    '--color-chart-border':                   '#e0e0ff',
    '--color-chart-bg':                       'rgba(230, 159, 0, 0.25)',
    '--color-thrift-item-text':               '#0a0a20',
    '--color-thrift-img-border':              '#f0f0ff',
    '--color-source-card-border':             '#e0e0ff',
    '--color-source-meta-text':               '#7070a0',
    '--color-search-icon':                    '#555570',
    '--color-search-text':                    '#d0d0ee',
    '--color-account-link':                   '#0072B2',
    '--color-settings-info-text':             '#8080aa',
    '--color-settings-back-link':             '#0072B2',
    '--color-settings-link':                  '#0072B2',
    '--color-settings-divider':               '#2a2a4a',
    '--color-settings-option-text':           '#1a1a30',
    '--color-settings-option-icon':           '#101025',
    '--color-settings-donate-accent':         '#56B4E9',
    '--color-settings-desc-text':             '#6060aa',
    '--color-settings-priority-bg':           '#e8e8f8',
    '--color-settings-separator':             '#2a2a4a',
  },


  // Blue-yellow color blindness
  // Avoids blue/yellow pairs. Uses teal vs red/orange instead.
  tritanopia: {
    '--color-page-bg':                        'rgb(30, 20, 20)',
    '--color-phone-bezel':                    '#2a1010',
    '--color-phone-screen':                   '#fff5f5',
    '--color-phone-content-bg':               'rgb(25, 15, 15)',
    '--color-dynamic-island-bg':              '#100000',
    '--color-footer-text':                    'rgb(140, 90, 90)',
    '--color-header-primary':                 '#2a1010',
    '--color-header-secondary':               '#1a0808',
    '--color-progress-track':                 '#4a2a2a',
    '--color-progress-fill':                  '#cc2200',
    '--color-progress-text':                  '#fff5f5',
    '--color-btn-primary-bg':                 '#008080',
    '--color-btn-primary-border':             '#00aaaa',
    '--color-btn-primary-text':               '#ffffff',
    '--color-btn-primary-active-bg':          '#006060',
    '--color-btn-primary-active-border':      '#008080',
    '--color-btn-secondary-bg':               '#f5e8e8',
    '--color-btn-secondary-text':             '#2a1010',
    '--color-btn-secondary-border':           '#ccaaaa',
    '--color-btn-secondary-active-bg':        '#e0c8c8',
    '--color-btn-secondary-active-border':    '#aa8888',
    '--color-nav-bg':                         'rgba(25, 8, 8, 0.8)',
    '--color-nav-item-bg':                    'rgba(45, 15, 15, 0.7)',
    '--color-nav-item-text':                  '#ffe8e8',
    '--color-nav-item-selected-bg':           '#008080',
    '--color-results-panel-bg':               '#cc4400',
    '--color-result-card-border':             '#ffe8e8',
    '--color-result-hide-bar':                '#ffe8e8',
    '--color-result-view-more-bg':            'rgba(255,255,255,0.07)',
    '--color-result-view-more-border':        '#ccaaaa',
    '--color-result-source-label':            '#5a3030',
    '--color-result-badge-text':              '#fff5f5',
    '--color-result-badge-bg':                '#3a1818',
    '--color-result-title-text':              '#1a0808',
    '--color-infobox-bg':                     'rgb(255, 242, 242)',
    '--color-infobox-text':                   '#1a0808',
    '--color-ai-warn-neutral':                '#888888',
    '--color-ai-warn-mid':                    '#cc4400',
    '--color-ai-warn-hot':                    '#cc0000',
    '--color-chart-border':                   '#ffe8e8',
    '--color-chart-bg':                       'rgba(200, 50, 0, 0.18)',
    '--color-thrift-item-text':               '#1a0808',
    '--color-thrift-img-border':              '#ffe8e8',
    '--color-source-card-border':             '#ffe8e8',
    '--color-source-meta-text':               '#aa7070',
    '--color-search-icon':                    '#604040',
    '--color-search-text':                    '#eecccc',
    '--color-account-link':                   '#008080',
    '--color-settings-info-text':             '#aa6060',
    '--color-settings-back-link':             '#008080',
    '--color-settings-link':                  '#008080',
    '--color-settings-divider':               '#4a2020',
    '--color-settings-option-text':           '#2a1010',
    '--color-settings-option-icon':           '#1a0808',
    '--color-settings-donate-accent':         '#cc2200',
    '--color-settings-desc-text':             '#7a4040',
    '--color-settings-priority-bg':           '#f8eaea',
    '--color-settings-separator':             '#4a2020',
  },

  // Light mode
  light_mode: {
    '--color-page-bg':                        'rgb(220, 225, 230)',
    '--color-phone-bezel':                    '#aaaaaa',
    '--color-phone-screen':                   '#f8f9fa',
    '--color-phone-content-bg':               'rgb(240, 243, 246)',
    '--color-dynamic-island-bg':              '#1a1a1a',
    '--color-footer-text':                    'rgb(100, 110, 120)',
    '--color-header-primary':                 '#1a1f24',
    '--color-header-secondary':               '#2a3038',
    '--color-progress-track':                 '#c8cdd2',
    '--color-progress-fill':                  '#0054E9',
    '--color-progress-text':                  '#1a1f24',
    '--color-feed-ctrl-bg':                   'rgba(0, 0, 0, 0.08)',
    '--color-feed-ctrl-border':               'rgba(0, 0, 0, 0.2)',
    '--color-feed-ctrl-border-dim':           'rgba(0, 0, 0, 0.1)',
    '--color-feed-sel-bg':                    'rgba(0, 0, 0, 0.08)',
    '--color-feed-sel-border':                'rgba(0, 0, 0, 0.2)',
    '--color-feed-sel-text':                  'rgba(20, 20, 20, 0.8)',
    '--color-feed-sel-hover-bg':              'rgba(0, 0, 0, 0.14)',
    '--color-feed-sel-dark-bg':               'rgba(0, 84, 233, 0.85)',
    '--color-feed-sel-dark-bg-light':         'rgba(0, 84, 233, 0.7)',
    '--color-feed-sel-border-dim':            'rgba(0, 0, 0, 0.1)',
    '--color-feed-sel-border-top':            'rgba(255, 255, 255, 0.5)',
    '--color-feed-sel-selected-text':         '#ffffff',
    '--color-feed-sel-active-text':           '#ffffff',
    '--color-btn-primary-bg':                 '#0054E9',
    '--color-btn-primary-border':             '#005cfa',
    '--color-btn-primary-text':               '#ffffff',
    '--color-btn-primary-active-bg':          '#004ac9',
    '--color-btn-primary-active-border':      '#004bce',
    '--color-btn-secondary-bg':               '#ffffff',
    '--color-btn-secondary-text':             '#1a1f24',
    '--color-btn-secondary-border':           '#c8cdd2',
    '--color-btn-secondary-active-bg':        '#e8ecf0',
    '--color-btn-secondary-active-border':    '#aab0b8',
    '--color-nav-bg':                         'rgba(200, 210, 220, 0.85)',
    '--color-nav-item-bg':                    'rgba(180, 190, 200, 0.6)',
    '--color-nav-item-text':                  '#1a1f24',
    '--color-nav-item-selected-bg':           '#0054E9',
    '--color-results-panel-bg':               '#e8ecf0',
    '--color-result-card-border':             '#ffffff',
    '--color-result-hide-bar':                '#dde0e4',
    '--color-result-view-more-bg':            'rgba(0, 0, 0, 0.04)',
    '--color-result-view-more-border':        '#c8cdd2',
    '--color-result-source-label':            '#5a6470',
    '--color-result-badge-text':              '#ffffff',
    '--color-result-badge-bg':                '#3a4550',
    '--color-result-title-text':              '#1a1f24',
    '--color-infobox-bg':                     '#ffffff',
    '--color-infobox-text':                   '#1a2a3a',
    '--color-chart-border':                   '#dde0e4',
    '--color-chart-bg':                       'rgba(255, 204, 50, 0.2)',
    '--color-thrift-item-text':               '#1a1f24',
    '--color-thrift-img-border':              '#dde0e4',
    '--color-source-card-border':             '#dde0e4',
    '--color-source-meta-text':               '#7a8490',
    '--color-search-icon':                    '#c8cdd2',
    '--color-search-text':                    '#5a6470',
    '--color-account-link':                   '#0054E9',
    '--color-settings-info-text':             'rgb(80, 90, 100)',
    '--color-settings-back-link':             '#0054E9',
    '--color-settings-link':                  '#0054E9',
    '--color-settings-text':                  'rgb(32, 32, 32)',
    '--color-settings-divider':               '#c8cdd2',
    '--color-settings-option-text':           '#131314',
    '--color-settings-option-icon':           '#2a3038',
    '--color-settings-donate-accent':         '#5A3AD8',
    '--color-settings-desc-text':             '#5a6470',
    '--color-settings-priority-bg':           '#ffffff',
    '--color-settings-separator':             '#c8cdd2',
  },

};